drop procedure allin.ActualizarCliente,allin.ActualizarVisibilidad,allin.actualizarIntentos,allin.actualizarStock,allin.agregarCalificacion,allin.agregarCompra,allin.agregarNuevaEmpresa,allin.agregarNuevaOferta,allin.agregarNuevaVisibilidad,allin.averiguarStock,
allin.buscarCamposDeUsuario,allin.buscarIdCliente,allin.buscarIdEmpresa,allin.buscarIdPorPublicacion,allin.buscarIdUsuario,allin.buscarMaximaOferta,allin.buscarPrecio,allin.buscarUnSoloCliente,
allin.buscarUnaSolaEmpresa,allin.buscarUnaVisibilidad,allin.buscarUsuarioCliente,allin.buscarUsuarioEmpresa,allin.cambiarConGanador,allin.darDeBajaAlCliente,allin.darDeBajavISIBILIDAD,allin.filtrarRol,allin.filtrarRubro,allin.listaDeEmpresas,
allin.listaDePubSinCalificar,allin.listaDePublicaciones,allin.listaDePublicacionesSinFacturar,allin.listaDeVisibilidades,allin.listaSubastasSinConfirmarGanador,allin.obtenerEstadoDelId,
  allin.agregarItemFactura,allin.agregarNuevaPublicacion,allin.agregarNuevoCliente,allin.agregarNuevoRol,allin.agregarRespuesta,allin.agregarUnaPregunta,
 allin.buscarDatosPublicacion, allin.buscarDuracionVisibilidad, allin.buscarIdRol, allin.buscarNombreUsuario, allin.buscarPublicador, allin.buscarPublicadorCod,
 allin.darDeAltaUsuario,allin.darDeBajaAEmpresa,allin.darDeBajaRol
drop procedure
allin.publicacionAFacturar,allin.actualizarEmpresa,allin.actualizarEstadoDelUsuario,allin.actualizarEstadoRol,allin.agregarFactura,allin.agregarFuncionabilidadAlRol,
allin.facturasTop,allin.historialCalificacionesOtorgadas,allin.historialCalificacionesRecibidas,allin.historialCompras,allin.historialOfertas,
allin.listaDeCliente,allin.listaDeMisPublicaciones,allin.listadoDeFuncionabilidades,allin.listadoDePreguntasAResponder,
allin.listadoDeRespYProducto,allin.listadoMayoresSinCalificaciones,allin.listadoMayoresFacturacion,allin.listadoVendedoresQueVendenMenos,
allin.nroFactura,allin.obtenerCodRubro,allin.obtenerDescripcionRubro,allin.obtenerEstado,allin.obtenerNombreIdRol,allin.obtenerPregunta,allin.obtenerVisibilidad,allin.quitarRol,allin.seleccionVisibilidadNotNull,
allin.verificarEstado,allin.verificarTresGratuitas,allin.actualizarContraseña,allin.esBonificada,allin.listaDeCliente2,allin.listadoMayoresCalificaciones,
allin.editarPublicacionBorrador,allin.editarPublicacionPublicada,allin.agregarItemFacturaComision,allin.agregarItemFacturaPublicacion

drop procedure listadepublicacionessinfacturar,allin.obteneridrol,allin.quitarpublicacionrubro,allin.editarPublicacionBorradorAPublicada,allin.buscarIdMaximaOferta,allin.cambiarafacturada, allin.actualizarNombreRol,allin.agregarNuevaEmpresaUsuario,allin.agregarNuevoClienteUsuario,allin.agregarPublicacionRubro,allin.buscarFuncionalidades,allin.buscarMiIDUsuario,allin.buscarUsuarioCod,
allin.darDeBajaAUsuario,allin.estaHabilitado,allin.listadoDeFunc,allin.obtenerCodEstadoPublicacion,allin.obtenerCodTipoPublicacion
drop procedure allin.obtenerNombreTipoPublicacion,allin.obtenerTodosLosRoles,allin.quitarPublicacionRubro,allin.editarPublicacionBorradorAPublicada,allin.cambiarafacturada