drop procedure ActualizarCliente,ActualizarVisibilidad,actualizarIntentos,actualizarStock,agregarCalificacion,agregarCompra,agregarNuevaEmpresa,agregarNuevaOferta,agregarNuevaVisibilidad,averiguarStock,buscarCamposDeUsuario,buscarIdCliente,buscarIdEmpresa,buscarIdPorPublicacion,buscarIdUsuario,buscarMaximaOferta,buscarPrecio,buscarUnSoloCliente,buscarUnaSolaEmpresa,buscarUnaVisibilidad,buscarUsuarioCliente,buscarUsuarioEmpresa,cambiarConGanador,darDeBajaAlCliente,darDeBajavISIBILIDAD,filtrarRol,filtrarRubro,listaDeEmpresas,
listaDePubSinCalificar,listaDePublicaciones,listaDePublicacionesSinFacturar,listaDeVisibilidades,listaSubastasSinConfirmarGanador,obtenerEstadoDelId,
  agregarItemFactura,agregarNuevaPublicacion,agregarNuevoCliente,agregarNuevoRol,agregarRespuesta,agregarUnaPregunta,
 buscarDatosPublicacion, buscarDuracionVisibilidad, buscarIdRol, buscarNombreUsuario, buscarPublicador, buscarPublicadorCod,
 darDeAltaUsuario,darDeBajaAEmpresa,darDeBajaRol
drop procedure
publicacionAFacturar,actualizarEmpresa,actualizarEstadoDelUsuario,actualizarEstadoRol,agregarFactura,agregarFuncionabilidadAlRol,
facturasTop,historialCalificacionesOtorgadas,historialCalificacionesRecibidas,historialCompras,historialOfertas,
listaDeCliente,listaDeMisPublicaciones,listadoDeFuncionabilidades,listadoDePreguntasAResponder,
listadoDeRespYProducto,listadoMayoresSinCalificaciones,listadoMayoresFacturacion,listadoVendedoresQueVendenMenos,
nroFactura,obtenerCodRubro,obtenerDescripcionRubro,obtenerEstado,obtenerNombreIdRol,obtenerPregunta,obtenerVisibilidad,quitarRol,seleccionVisibilidadNotNull,
verificarEstado,verificarTresGratuitas,actualizarContraseña,esBonificada,listaDeCliente2,listadoMayoresCalificaciones,
editarPublicacionBorrador,editarPublicacionPublicada,agregarItemFacturaComision,agregarItemFacturaPublicacion

drop procedure actualizarNombreRol,agregarNuevaEmpresaUsuario,agregarNuevoClienteUsuario,agregarPublicacionRubro,buscarFuncionalidades,buscarMiIDUsuario,buscarUsuarioCod,
darDeBajaAUsuario,estaHabilitado,listadoDeFunc,obtenerCodEstadoPublicacion,obtenerCodTipoPublicacion,
obtenerNombreTipoPublicacion,obtenerTodosLosRoles,quitarPublicacionRubro,buscaridmaximaoferta,editarpublicacionborradorapublicada